### ISSUE TITLE
Android SDK not being installed after importing as a submodule

### ISSUE THREAD

**Issue by culudamar** [raymond-chetty/codespaces-AndroidSDK-CE#3]
When I import this submodule and try to build [Universal Android Media App (UAMP)](https://github.com/android/uamp), I get SDK not installed error. Steps:
1. Open UAMP in a new codespace.
2. Run "git submodule add https://github.com/raymond-chetty/codespaces-AndroidSDK-CE .devcontainer" in terminal.
3. Run "./gradlew build" in terminal.
4. Observe the error that SDK not installed.

**Comment by raymond-chetty** [comment]
I think you want to contact the project for support.... https://github.com/android/uamp/tree/main?tab=readme-ov-file#support

That said, it's possible you need to install additional packages, or that the target version for the project, 30, is older than the installed version for the devcontainer, 33.

I'm going to close this issue because it's not necessarily related to this project. Please review the support information for the uamp project and maybe the android sdk documentation.

Android packages documentation 
https://developer.android.com/tools/sdkmanager

Android sdk versions
https://github.com/raymond-chetty/codespaces-AndroidSDK-CE/blob/develop/devcontainer.json#L25
https://github.com/android/uamp/blob/main/build.gradle#L21

Android 11 has sdk version 30
https://developer.android.com/about/versions/11/setup-sdk

Maybe try changing 33 ->30 in your devcontainer submodule checkout?

Auto download missing packages
https://developer.android.com/studio/intro/update#download-with-gradle

Good Luck!
